version: "3"
services:
  stash:
    #image: stashapp/stash
    image: stash-s6:alpine
    ports:
      - 9999:9999
    volumes:
      - E:/Workspace/stash-dev-media:/media/stash
      - E:/Workspace/stash-dev/config:/config
      - E:/Workspace/stash-dev/root:/root/.stash
      - data:/data
      - pip:/pip-install
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  data:
    external: true
  pip:
    external: true
