version: "3"
services:
  stash:
    image: stash-s6:alpine
    ports:
      - 9999:9999
    environment:
      - PUID=1000
      - PGID=1000
    #  - MIGRATE=TRUE
    volumes:
      - /mnt/media/stash:/media/stash
      - pip:/pip-install
      - config:/config
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  pip:
    external: true
  config:
    external: true