name: develop-build
on:
  push:
    branches:
      - main
    paths:
      - 'dockerfile/**'
      - 'stash/**'
      - 'VERSION'
  workflow_dispatch:
  repository_dispatch:
    types: [upstream_update]
  schedule:
    - cron: '0 0 */7 * *'

jobs:
  docker-alpine:
    uses: ./.github/workflows/docker-alpine.yml
    with:
      upstream: development
      tags: |-
        alpine-develop
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  docker-hwaccel:
    uses: ./.github/workflows/docker-hwaccel.yml
    with:
      upstream: development
      tags: |-
        hwaccel-develop
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  docker-jf7:
    uses: ./.github/workflows/docker-hwaccel.yml
    with:
      upstream: development
      tags: hwaccel-develop-jf7
      buildarg: "FFMPEG_VERSION=7"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}