name: docker-alpine-build
on: 
  workflow_call:
    inputs:
      upstream:
        require: true
        type: string
      pr:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

env:
  IMAGE_NAME: stash-s6

permissions:
  packages: write
  contents: read

jobs:
  docker-alpine-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            ${{ inputs.tag }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - name: build and push multi-arch alpine image
        uses: docker/build-push-action@v5
        with:
          push: true
          provenance: false
          file: dockerfile/pr.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
          build-args: |
            UPSTREAM_TYPE=${{ inputs.upstream }}
            TARGET_BRANCH=${{ inputs.pr }}