name: docker-hawccel-lscr-matrix-build
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

env:
  IMAGE_NAME: stash-s6

jobs:
  build-image:
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: setup image names
        run: |
          echo "GHCR_IMAGE=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}" >> "$GITHUB_ENV"
          echo "DHIO_IMAGE=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}" >> "$GITHUB_ENV"
      - name: build hwaccel-base for local use
        uses: docker/build-push-action@v4
        with:
          push: true
          file: hwaccel-base.Dockerfile
          build-args: |
            S6_OVERLAY_ARCH=${{ matrix.architecture }}
          platforms: linux/amd64,linux/arm64
          tags: |
            localhost:5000/stash-s6:hwaccel-base
      - name: build hwaccel-lscr amd64
        uses: docker/build-push-action@v4
        with:
          push: true
          file: hwaccel-lscr.Dockerfile
          build-args: |
            S6_OVERLAY_ARCH=x86_64
            UPSTREAM_IMAGE=localhost:5000/stash-s6
          platforms: linux/amd64
          tags: |
            ${{ env.GHCR_IMAGE }}:hwaccel-lscr-amd64
      - name: build hwaccel-lscr arm64
        uses: docker/build-push-action@v4
        with:
          push: true
          file: hwaccel-lscr.Dockerfile.aarch64
          build-args: |
            S6_OVERLAY_ARCH=aarch64
            UPSTREAM_IMAGE=localhost:5000/stash-s6
          platforms: linux/arm64
          tags: |
            ${{ env.GHCR_IMAGE }}:hwaccel-lscr-arm64
  create-manifests:
    needs: [builds-matrix]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: create manifest for GHCR/hwaccel-lscr
        run: |
          docker manifest create \
            ${{ env.GHCR_IMAGE }}:hwaccel-lscr \
            --amend ${{ env.GHCR_IMAGE }}:hwaccel-lscr-amd64 \
            --amend ${{ env.GHCR_IMAGE }}:hwaccel-lscr-arm64
          docker manifest push ${{ env.GHCR_IMAGE }}:hwaccel-lscr