name: release-build
on:
  push:
    branches:
      - main
    paths:
      - 'dockerfile/**'
      - 'stash/**'
      - 'VERSION'
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  docker-alpine:
    uses: ./.github/workflows/docker-alpine.yml
    with:
      upstream: latest
      tags: |-
        alpine
        latest
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  docker-hwaccel:
    uses: ./.github/workflows/docker-hwaccel.yml
    with:
      upstream: latest
      tags: |-
        hwaccel
        hwaccel-jf
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}