name: release-build
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  docker-alpine:
    uses: ./.github/workflows/docker-alpine.yml
    with:
      upstream: latest
      tag1: alpine
      tag2: latest
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  docker-hwaccel:
    uses: ./.github/workflows/docker-hwaccel.yml
    with:
      upstream: latest
      tag1: hwaccel
      tag2: hwaccel-jf
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}